apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:

      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db-order:3306/order-service?allowPublicKeyRetrieval=true
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: domdevs/order-service:latest
          name: order-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9193
  selector:
    app: order-service
status:
  loadBalancer: {}